//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaTratorPecas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data source=YURI\\SQLSERVER14;\r\nInitial Catalog=BD_TRATORPECAS;\r\nUID=sa;\r\npwd=eco@" +
            "4067")]
        public string Conexao {
            get {
                return ((string)(this["Conexao"]));
            }
            set {
                this["Conexao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;   
 Password=masterkey;   
 Database=d:\dados\tratorpecas\ecodados.eco;   
 DataSource=localhost;   
 Port=3050;   
 Dialect=3;   
 Charset=NONE;   
 Role=;   
 Connection lifetime=15;   
 Pooling=true;   
 Packet Size=8192;   
 ServerType=0 ;")]
        public string ConexaoFB {
            get {
                return ((string)(this["ConexaoFB"]));
            }
            set {
                this["ConexaoFB"] = value;
            }
        }
    }
}
